<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class PostTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic feature test.
     */
    public function test_can_create_user_with_posts(): void
    {
        $user = User::factory()->create([
            'name' => 'Janne Doe',
            'email' => 'jannedoe@example.com',
        ]);

        $user->posts()->createMany([
            [
                'user_id' => $user->id,
                'title' => 'Martin is an engineer',
                'body' => 'Martin works at Abbott company',
            ], [
                'user_id' => $user->id,
                'title' => 'Lynn is a lawyer',
                'body' => 'Lynn works at Kub company',
            ],
        ]);

        $this->assertTrue(true);
        $this->assertCount(2, $user->posts);
    }
}
