<?php

    namespace Tests\Unit;

    use App\Models\Comment;
    use App\Models\Post;
    use App\Models\User;
    use Illuminate\Foundation\Testing\RefreshDatabase;
    use Illuminate\Foundation\Testing\WithFaker;
    use Tests\TestCase;

    class CommentTest extends TestCase
    {
        use RefreshDatabase, WithFaker;

        protected function setUp(): void
        {
            parent::setUp(); // TODO: Change the autogenerated stub

            $this->user         = User::factory()->create();
        }

        // TESTING "polymorphic relation"
        public function test_comment_can_be_created_for_a_post()
        {
            $post = Post::create([
                'title' => $this->faker->sentence(7),
                'body' => $this->faker->sentence(200),
                'user_id'   => $this->user->id
            ]);

            $commentData = [
                'body'      => $this->faker->sentence(200),
                'user_id'   => $this->user->id
            ];

            $comment = $post->comments()->create($commentData);

            $this->assertInstanceOf(Comment::class, $comment);
            $this->assertEquals($commentData['body'], $comment->body);
            $this->assertEquals($post->id, $comment->commentable_id);
            $this->assertEquals(Post::class, $comment->commentable_type);
        }
    }
